<li>
											<div class="slideBox_left"><a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]"></a></div>
											<div class="slideBox_right">
												<div class="slideBox_tit"><a href="[field:arcurl/]">[field:title/]</a></div>
												<div class="slideBox_desc">[field:description function="cn_substr(@me,100)"/]...<a href="[field:arcurl/]">[详细]</a></div>
												<div class="slideBox_date">[field:pubdate function=GetDateMK(@me)/]</div>
											</div>
										</li>