
<field:byxx itemname="毕业学校" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:byxx>

<field:zc itemname="职称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zc>

<field:bgdd itemname="办公地点" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bgdd>

<field:yjfx itemname="研究方向" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yjfx>

<field:dzyj itemname="电子邮件" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:dzyj>

<field:yjxm itemname="研究项目" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yjxm>
