<?php
$z[0]=Array("pubdate"," \$ntime = time(); \$day3 = 3600 * 24 * 0; if((\$ntime - @me) < \$day3) @me = \"class='last'\"; else @me = \"\"; ",4,153);
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",268,314);
$z[1][4]['function']="strftime(\"%d\",@me)";
$z[2]=Array("pubdate","",364,413);
$z[2][4]['function']="strftime(\"%Y-%m\",@me)";
$z[3]=Array("title","",528,542);
$z[4]=Array("description","",614,663);
$z[4][4]['function']="cn_substr(@me,80)";

?>