<?php
$z[0]=Array("pubdate"," \$ntime = time(); \$day3 = 3600 * 24 * 3; if((\$ntime - @me) < \$day3) @me = \"class='last'\"; else @me = \"\"; ",4,153);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",174,189);
$z[2]=Array("pubdate","",271,317);
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("pubdate","",367,416);
$z[3][4]['function']="strftime(\"%Y-%m\",@me)";
$z[4]=Array("title","",531,545);
$z[5]=Array("description","",617,666);
$z[5][4]['function']="cn_substr(@me,80)";

?>