<?php
$z[0]=Array("global","",175,197);
$z[0][4]['name']="cfg_tel";
$z[1]=Array("global","",241,265);
$z[1][4]['name']="cfg_email";
$z[2]=Array("global","",307,329);
$z[2][4]['name']="cfg_add";
$z[3]=Array("global","",371,393);
$z[3][4]['name']="cfg_zip";
$z[4]=Array("flink","[field:link/]",540,599);
$z[4][4]['row']="99";
$z[4][4]['type']="text";
$z[5]=Array("arclist"," \r\n						<img src=\"[field:picname/]\" />\r\n						",754,848);
$z[5][4]['row']="1";
$z[5][4]['idlist']="25";
$z[6]=Array("global","",946,972);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("field","",1041,1068);
$z[7][4]['name']="phpurl";

?>