<?php
$z[0]=Array("global","",216,241);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("field","",555,600);
$z[1][4]['name']="typeid";
$z[1][4]['function']="GetTopid(@me)";
$z[2]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",737,887);
$z[2][4]['typeid']="1";
$z[3]=Array("channel","\r\n						<li><a href='[field:typeurl/]'>[field:typename/]</a> </li>\r\n						",918,1041);
$z[3][4]['type']="son";
$z[3][4]['typeid']="1";
$z[4]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",1070,1220);
$z[4][4]['typeid']="6";
$z[5]=Array("channel","\r\n						<li><a href='[field:typeurl/]'>[field:typename/]</a> </li>\r\n						",1251,1374);
$z[5][4]['type']="son";
$z[5][4]['typeid']="6";
$z[6]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",1403,1554);
$z[6][4]['typeid']="13";
$z[7]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",1571,1722);
$z[7][4]['typeid']="18";
$z[8]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",1739,1890);
$z[8][4]['typeid']="19";
$z[9]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",1907,2058);
$z[9][4]['typeid']="20";
$z[10]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",2075,2226);
$z[10][4]['typeid']="21";
$z[11]=Array("type","\r\n				<li class=\"nLi hline\" id=\"t[field:id/]\">\r\n					<h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n					",2243,2394);
$z[11][4]['typeid']="22";

?>