<?php
$z[0]=Array("field","",60,118);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n						<li><a href=\"[field:typeurl/]\">—[field:typename/]</a></li>\r\n						",207,410);
$z[1][4]['type']="son";
$z[1][4]['row']="99";
$z[1][4]['currentstyle']="<li class=\"\"><a href=\"~typelink~\" ~rel~>—~typename~</a></li>";
$z[2]=Array("global","",477,509);
$z[2][4]['name']="cfg_templets_skin";

?>