<?php
$z[0]=Array("global","",239,267);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",295,321);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",364,393);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",435,493);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",517,549);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",640,672);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",744,776);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",847,882);
$z[7][4]['filename']="head.htm";
$z[8]=Array("field","",1013,1042);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n					<li>\r\n						<a href=\"[field:arcurl/]\">\r\n							<div class=\"item_pic\"><img src=\"[field:picname/]\" /></div>\r\n							<div class=\"item_right\">\r\n								<div class=\"item_tit\">[field:title/]</div>\r\n								<div class=\"item_desc\">[field:description function=\"cn_substr(@me,200)\"/]</div>\r\n								<div class=\"item_date\">[field:pubdate function=\"MyDate('Y-m-d H:i:s',@me)\"/]</div>\r\n							</div>\r\n						</a>\r\n					</li>\r\n					",1088,1549);
$z[9][4]['pagesize']="10";
$z[10]=Array("pagelist","",1591,1643);
$z[10][4]['istitem']="index,pre,next,info,end,";
$z[11]=Array("channel","\r\n						<li><a href=\"[field:typeurl/]\">—[field:typename/]</a></li>\r\n						",1834,1950);
$z[11][4]['type']="top";
$z[12]=Array("global","",2017,2049);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("include","",2140,2177);
$z[13][4]['filename']="footer.htm";

?>